# SPDX-License-Identifier: MIT OR Apache-2.0
# SPDX-FileCopyrightText: 2026 Jarrad Hope

[package]
name = "pipeline-stage"
version = "0.0.1"
edition = "2021"
license = "MIT OR Apache-2.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
daemon-vhc-sdk-v2 = { path = "../../sdk/daemon-vhc-sdk-v2" }
ciborium = "0.2"
