// SPDX-License-Identifier: MIT OR Apache-2.0
// SPDX-FileCopyrightText: 2026 Jarrad Hope

//! `SavedPresence` — the named, reusable presence a user can pick (work package W2-F).
//!
//! Ported from libpurple's `PurpleSavedPresence` (`purplesavedpresence.c`): an auto-identified,
//! named presence carrying a [`PresencePrimitive`], an optional status message + emoji, a
//! last-used timestamp, and a use-count. Unlike [`crate::details`] (pure behavior over existing
//! DTOs), this **is** a new wire DTO — it crosses the wire as `ApiResponse::SavedPresences` and
//! inside the `Presence{Save}` request — so it derives serde + feature-gated `Arbitrary` and is
//! mirrored in `daemon-api.cddl` (tagged `wire v37`).
//!
//! It reuses the existing [`PresencePrimitive`] (do not duplicate the `src/details.rs` predicates)
//! and the birb subsequence matcher from `src/matching.rs` for [`SavedPresence::matches`].

use crate::PresencePrimitive;
use serde::{Deserialize, Serialize};
use std::sync::atomic::{AtomicU64, Ordering};
use std::time::{SystemTime, UNIX_EPOCH};

/// Process-unique counter mixed into generated ids so two mints in the same nanosecond differ.
static ID_SALT: AtomicU64 = AtomicU64::new(0);

/// A named, reusable saved presence (← `PurpleSavedPresence`).
///
/// **Equality caveat:** the derived [`PartialEq`]/[`Eq`] (required by the wire enums) compares
/// EVERY field including `id`. libpurple's `purple_saved_presence_equal` deliberately ignores `id`
/// (two freshly-minted presences with different random ids are "equal"); that domain notion is the
/// separate [`SavedPresence::equal`] method + the NULL-aware [`saved_presence_equal`] free fn.
#[cfg_attr(feature = "arbitrary", derive(arbitrary::Arbitrary))]
#[derive(Clone, Debug, Default, PartialEq, Eq, Serialize, Deserialize)]
pub struct SavedPresence {
    /// The stable identifier (auto-generated by [`SavedPresence::new`] / [`SavedPresence::ensure_id`]
    /// when unset, mirroring `purple_saved_presence_constructed`).
    pub id: String,
    /// The human name of the saved presence, when set.
    #[serde(default)]
    pub name: Option<String>,
    /// The presence primitive (default [`PresencePrimitive::Offline`]).
    pub primitive: PresencePrimitive,
    /// The status message, when set.
    #[serde(default)]
    pub message: Option<String>,
    /// The emoji / mood, when set.
    #[serde(default)]
    pub emoji: Option<String>,
    /// Unix seconds this presence was last used (`None` = never), mirroring `last_used`.
    #[serde(default)]
    pub last_used: Option<u64>,
    /// The number of times this presence has been activated (`use_count`).
    #[serde(default)]
    pub use_count: u64,
}

impl SavedPresence {
    /// A new saved presence with `primitive` and a freshly-minted id
    /// (← `purple_saved_presence_new`, whose `constructed` mints a random id).
    pub fn new(primitive: PresencePrimitive) -> Self {
        Self {
            id: Self::gen_id(),
            primitive,
            ..Self::default()
        }
    }

    /// Ensure the id is set, minting a fresh one if it is empty
    /// (← `purple_saved_presence_constructed`: mint only when `birb_str_is_empty(id)`).
    pub fn ensure_id(&mut self) {
        if self.id.is_empty() {
            self.id = Self::gen_id();
        }
    }

    /// Mint a fresh unique id (nanosecond clock + process-unique counter, formatted UUID-shaped so
    /// it reads like `purple_saved_presence`'s `g_uuid_string_random()` — no external `uuid` dep).
    fn gen_id() -> String {
        let nanos = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .map(|d| d.as_nanos())
            .unwrap_or(0);
        let salt = ID_SALT.fetch_add(1, Ordering::Relaxed);
        // 128 bits of (time || counter), rendered in the 8-4-4-4-12 hex UUID grouping.
        let hi = (nanos as u64) ^ (salt << 1);
        let lo = ((nanos >> 64) as u64).wrapping_add(salt);
        format!(
            "{:08x}-{:04x}-{:04x}-{:04x}-{:012x}",
            hi & 0xffff_ffff,
            (hi >> 32) & 0xffff,
            (hi >> 48) & 0xffff,
            lo & 0xffff,
            (lo >> 16) & 0xffff_ffff_ffff,
        )
    }

    /// Domain equality (← `purple_saved_presence_equal`), which **ignores `id`**: compares
    /// `last_used`, `use_count`, `name`, `primitive`, `message`, `emoji`. `Option` equality
    /// reproduces the birb NULL rules exactly (both-`None` equal; one-`None` unequal).
    pub fn equal(&self, other: &SavedPresence) -> bool {
        self.last_used == other.last_used
            && self.use_count == other.use_count
            && self.name == other.name
            && self.primitive == other.primitive
            && self.message == other.message
            && self.emoji == other.emoji
    }

    /// Filter (← `purple_saved_presence_matches`): an empty/`None` needle matches; else a caseless
    /// subsequence match (birb `str_matches`) against `name` then `message`, then an **exact** match
    /// against `emoji` (`birb_str_equal`).
    pub fn matches(&self, needle: Option<&str>) -> bool {
        let needle = match needle {
            None | Some("") => return true,
            Some(needle) => needle,
        };
        if let Some(name) = self.name.as_deref() {
            if crate::matching::str_matches(needle, name) {
                return true;
            }
        }
        if let Some(message) = self.message.as_deref() {
            if crate::matching::str_matches(needle, message) {
                return true;
            }
        }
        // Emoji is compared for exact equality (not a subsequence), matching `birb_str_equal`.
        self.emoji.as_deref() == Some(needle)
    }
}

/// NULL-aware domain equality (← `purple_saved_presence_equal`, full): `None`/`None` → true; one
/// `None` → false; both `Some` → [`SavedPresence::equal`].
pub fn saved_presence_equal(a: Option<&SavedPresence>, b: Option<&SavedPresence>) -> bool {
    match (a, b) {
        (None, None) => true,
        (Some(a), Some(b)) => a.equal(b),
        _ => false,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn default_presence() -> SavedPresence {
        SavedPresence::new(PresencePrimitive::Offline)
    }

    // -- properties + id ----------------------------------------------------

    #[test]
    fn sp_properties_roundtrip() {
        // ← /saved-presence/properties: every property set via the constructor round-trips.
        let p = SavedPresence {
            id: "leeloo dallas multipass".into(),
            name: Some("my saved status".into()),
            primitive: PresencePrimitive::Streaming,
            message: Some("I'm live on twitch at https://twitch.tv/rw_grim/".into()),
            emoji: Some("💀".into()),
            last_used: Some(1_700_000_000),
            use_count: 123,
        };
        assert_eq!(p.id, "leeloo dallas multipass");
        assert_eq!(p.name.as_deref(), Some("my saved status"));
        assert_eq!(p.primitive, PresencePrimitive::Streaming);
        assert_eq!(
            p.message.as_deref(),
            Some("I'm live on twitch at https://twitch.tv/rw_grim/")
        );
        assert_eq!(p.emoji.as_deref(), Some("💀"));
        assert_eq!(p.last_used, Some(1_700_000_000));
        assert_eq!(p.use_count, 123);
    }

    #[test]
    fn sp_generates_id() {
        // ← /saved-presence/generates-id: a constructed presence has a non-empty id.
        let p = SavedPresence::new(PresencePrimitive::Available);
        assert!(!p.id.is_empty(), "id must be auto-generated");
        // The primitive passed to `new` is preserved.
        assert_eq!(p.primitive, PresencePrimitive::Available);
        // Two mints differ.
        let q = SavedPresence::new(PresencePrimitive::Available);
        assert_ne!(p.id, q.id, "each mint is unique");
        // ensure_id is idempotent once set.
        let mut r = p.clone();
        let before = r.id.clone();
        r.ensure_id();
        assert_eq!(r.id, before);
    }

    // -- equal --------------------------------------------------------------

    #[test]
    fn sp_equal_null_null() {
        // ← /saved-presence/equal/null_null.
        assert!(saved_presence_equal(None, None));
    }

    #[test]
    fn sp_equal_null_a() {
        // ← /saved-presence/equal/null_a: NULL vs a presence → false.
        let b = default_presence();
        assert!(!saved_presence_equal(None, Some(&b)));
    }

    #[test]
    fn sp_equal_null_b() {
        // ← /saved-presence/equal/null_b: a presence vs NULL → false.
        let a = default_presence();
        assert!(!saved_presence_equal(Some(&a), None));
    }

    #[test]
    fn sp_equal_default() {
        // ← /saved-presence/equal/default: two defaults are equal DESPITE different ids.
        let a = default_presence();
        let b = default_presence();
        assert_ne!(a.id, b.id, "the two defaults have distinct minted ids");
        assert!(a.equal(&b));
        assert!(saved_presence_equal(Some(&a), Some(&b)));
    }

    #[test]
    fn sp_equal_last_used() {
        // ← /saved-presence/equal/last-used.
        let mut a = default_presence();
        let mut b = default_presence();
        let now = Some(1_700_000_000);
        let yesterday = Some(1_699_913_600);

        a.last_used = now;
        assert!(!a.equal(&b));
        b.last_used = now;
        assert!(a.equal(&b));
        b.last_used = yesterday;
        assert!(!a.equal(&b));
        a.last_used = None;
        assert!(!a.equal(&b));
        b.last_used = None;
        assert!(a.equal(&b));
    }

    #[test]
    fn sp_equal_use_count() {
        // ← /saved-presence/equal/use-count.
        let mut a = default_presence();
        let mut b = default_presence();
        a.use_count = 100;
        assert!(!a.equal(&b));
        b.use_count = 100;
        assert!(a.equal(&b));
        b.use_count = 101;
        assert!(!a.equal(&b));
    }

    #[test]
    fn sp_equal_name() {
        // ← /saved-presence/equal/name.
        let mut a = default_presence();
        let mut b = default_presence();
        a.name = Some("present".into());
        assert!(!a.equal(&b));
        b.name = Some("present".into());
        assert!(a.equal(&b));
        b.name = Some("future".into());
        assert!(!a.equal(&b));
        a.name = None;
        assert!(!a.equal(&b));
    }

    #[test]
    fn sp_equal_primitive() {
        // ← /saved-presence/equal/primitive.
        let mut a = default_presence();
        let mut b = default_presence();
        a.primitive = PresencePrimitive::Streaming;
        assert!(!a.equal(&b));
        b.primitive = PresencePrimitive::Idle;
        assert!(!a.equal(&b));
        b.primitive = PresencePrimitive::Streaming;
        assert!(a.equal(&b));
    }

    #[test]
    fn sp_equal_message() {
        // ← /saved-presence/equal/message.
        let mut a = default_presence();
        let mut b = default_presence();
        a.message = Some("sleeping...".into());
        assert!(!a.equal(&b));
        b.message = Some("working!".into());
        assert!(!a.equal(&b));
        a.message = Some("working!".into());
        assert!(a.equal(&b));
    }

    #[test]
    fn sp_equal_emoji() {
        // ← /saved-presence/equal/emoji.
        let mut a = default_presence();
        let mut b = default_presence();
        a.emoji = Some("💤".into());
        assert!(!a.equal(&b));
        b.emoji = Some("🏢".into());
        assert!(!a.equal(&b));
        a.emoji = Some("🏢".into());
        assert!(a.equal(&b));
    }

    // -- matches ------------------------------------------------------------

    #[test]
    fn sp_matches_accepts_null() {
        // ← /saved-presence/matches/accepts_null.
        assert!(default_presence().matches(None));
    }

    #[test]
    fn sp_matches_empty_string() {
        // ← /saved-presence/matches/empty_string.
        assert!(default_presence().matches(Some("")));
    }

    #[test]
    fn sp_matches_name() {
        // ← /saved-presence/matches/name: caseless subsequence over the name.
        let mut p = default_presence();
        p.name = Some("getting pidgy with it".into());
        assert!(p.matches(Some("pidgy")));
    }

    #[test]
    fn sp_matches_message() {
        // ← /saved-presence/matches/message: caseless subsequence over the message.
        let mut p = default_presence();
        p.message = Some("Uro666: purpelling to new heights".into());
        assert!(p.matches(Some("purpel")));
    }

    #[test]
    fn sp_matches_emoji() {
        // ← /saved-presence/matches/emoji: EXACT match over the emoji.
        let mut p = default_presence();
        p.emoji = Some("😴".into());
        assert!(p.matches(Some("😴")));
        // Emoji is exact, not subsequence: a different emoji does not match.
        assert!(!p.matches(Some("😀")));
    }

    #[test]
    fn sp_matches_none() {
        // ← /saved-presence/matches/none: a default presence (no name/message/emoji) matches nothing.
        assert!(!default_presence().matches(Some("away")));
    }
}
